name: lovisworld
favicon: null
layout_spectrum: 0.74789
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4b4b4b'
    - '#c4c4c4'
    - '#9e9e9e'
    - '#e1e1e1'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
